// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XwkbaLF4FQDXTI8FssC7-6hCq4BfhGI',
    appId: '1:863265955705:web:912692adf02dac12fd99a8',
    messagingSenderId: '863265955705',
    projectId: 'happy-messaging-b2b73',
    authDomain: 'happy-messaging-b2b73.firebaseapp.com',
    storageBucket: 'happy-messaging-b2b73.firebasestorage.app',
    measurementId: 'G-GNNZ06GG3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWwWLWrEmO83F2uNbI6hjIlXo8hSQR6Q',
    appId: '1:863265955705:android:8484ab9673c04c76fd99a8',
    messagingSenderId: '863265955705',
    projectId: 'happy-messaging-b2b73',
    storageBucket: 'happy-messaging-b2b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDOJDMAWbjObQ3vGq68_83td_vCgzNCE',
    appId: '1:863265955705:ios:e094ead910942a93fd99a8',
    messagingSenderId: '863265955705',
    projectId: 'happy-messaging-b2b73',
    storageBucket: 'happy-messaging-b2b73.firebasestorage.app',
    iosBundleId: 'com.example.receive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbDOJDMAWbjObQ3vGq68_83td_vCgzNCE',
    appId: '1:863265955705:ios:e094ead910942a93fd99a8',
    messagingSenderId: '863265955705',
    projectId: 'happy-messaging-b2b73',
    storageBucket: 'happy-messaging-b2b73.firebasestorage.app',
    iosBundleId: 'com.example.receive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XwkbaLF4FQDXTI8FssC7-6hCq4BfhGI',
    appId: '1:863265955705:web:5b2da9f4c4da9d32fd99a8',
    messagingSenderId: '863265955705',
    projectId: 'happy-messaging-b2b73',
    authDomain: 'happy-messaging-b2b73.firebaseapp.com',
    storageBucket: 'happy-messaging-b2b73.firebasestorage.app',
    measurementId: 'G-831MNHQ8TT',
  );
}
